# Generated by Django 4.2.10 on 2025-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bus_capacity_alter_driver_license_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='position',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bus',
        ),
        migrations.AddField(
            model_name='staff',
            name='boarding_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='bus_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='boarding_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bus_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
