# Generated by Django 4.2.10 on 2025-03-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_position_staff_department_remove_staff_bus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='bus_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bus_no',
        ),
        migrations.AddField(
            model_name='staff',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='accounts.bus'),
        ),
        migrations.AddField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.bus'),
        ),
    ]
