# Generated by Django 4.2.10 on 2025-03-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_staff_bus_no_remove_student_bus_no_staff_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student'), ('Driver', 'Driver'), ('Parent', 'Parent')], default='Student', max_length=20),
        ),
    ]
